[{
    id: 1244,
    title: 'Berlin Downtown Apartment',
    bedrooms: 2,
    bathrooms: 3,
    accomodates: 4,
    instant_bookable: 1,
    maximum_nights: 7,
    minimum_nights: 1,
    amenities: [{ label: "High End Electronics", value: "high_end_electronics" }],
    price: null,
},

{
    id: 5678,
    title: 'Luxury Home In Suburban Berlin',
    bedrooms: 2,
    bathrooms: 3,
    accomodates: 4,
    instant_bookable: 1,
    maximum_nights: 7,
    minimum_nights: 1,
    amenities: [{ label: "High End Electronics", value: "high_end_electronics" }],
    price: null,
},

{
    id: 1239,
    title: 'Luxury Ship in River',
    bedrooms: 2,
    bathrooms: 3,
    accomodates: 4,
    instant_bookable: 1,
    maximum_nights: 7,
    minimum_nights: 1,
    amenities: [{ label: "High End Electronics", value: "high_end_electronics" }],
    price: null,
},
{
    id: 3425,
    title: 'Guest House in Berlin',
    bedrooms: 2,
    bathrooms: 3,
    accomodates: 4,
    instant_bookable: 1,
    maximum_nights: 7,
    minimum_nights: 1,
    amenities: [{ label: "High End Electronics", value: "high_end_electronics" }],
    price: null,
}]